### PR TITLE
feat: build dw.js from source

### PR DESCRIPTION
**Pull request by sto3psl**
This is a direct port of the `dw.js` folder in https://github.com/datawrapper/datawrapper.

When I first started with this repo, I copied `dw.js` over (same as `embed.js`). This enabled me to quickly continue development. If there are changes necessary to `dw.js` that isn't ideal. 

That's why I copied everything here and updated some dependencies in the build. The tests can run, too.

Let me know if I missed anything or if this is a bad idea.

### CODE REVIEW

**Comment by gka** [comment]
I think it's sort of a bad idea because it means we now have three(!) locations for this source code.

* there still is the `dw.js` folder in the datawrapper repo (and we still need the library there as part of the chart editor)
* most parts of `dw.js` were already rewritten in modern JS code and live in the `shared` repo. This especially includes the dataset and csv parsing code.

Currently I already have to apply changes to the code (eg a recent csv parsing fix) in two places. It would be nice if we woudn't just turn this into three places.

Instead I had envisioned that we could at some point properly build the `dw.js` from the sources in `shared` (or wherever we decide to move them, chart-core seems fine) using rollup and buble/babel.

So far I never went through with this project, despite already refactoring most of the code. One major problem was my decision to refactor `dw.chart` as Svelte2 store which is now already sort of deprecated. So I guess it would be better to decouple our core classes from the frontend framework and find other ways to bind controls to chart properties.

**Comment by gka** [comment]
Here's an example for the code duplication:
* `purifyHtml` in `shared`: https://github.com/datawrapper/shared/blob/master/purifyHtml.js
* `purifyHtml` in `datawrapper` (as part of dw.utils): https://github.com/datawrapper/datawrapper/blob/node-publishing/dw.js/src/dw.utils.js#L154-L213
* `purifyHtml` in `chart-core` https://github.com/datawrapper/chart-core/pull/17/files#diff-5f5c83afd404daa289c5831d4d61a8fbR154-R213

**Comment by sto3psl** [comment]
It's not ideal in any way and I would love to just use `shared` everywhere. At the moment charts still rely on `dw.js`. I have some ideas about the current problems:

> there still is the dw.js folder in the datawrapper repo (and we still need the library there as part of the chart editor)

The datawrapper repo could install `@datawrapper/chart-core` and get `dw.js` from there, which reduces the locations to 2. 

I think that can be an acceptable temporary solution until we can get to the ideal dream state of having only `shared`.

> Instead I had envisioned that we could at some point properly build the dw.js from the sources in shared (or wherever we decide to move them, chart-core seems fine) using rollup and buble/babel.

That sounds great and could be a project after launch. `dw.js` doesn't change all that much and we can try to make sure that new features use `shared` functions and don't introduce new usage of `dw.js`. That way we slowly reduce the reliance on `dw.js`.

Is that an acceptable trade-off? Preview and Publish do need the file and this seems like a solution without too many problems.

**Comment by gka** [comment]
> The datawrapper repo could install @datawrapper/chart-core and get dw.js from there, which reduces the locations to 2.

That means that we now have a node dependency in our PHP app? This would change our deployment which is not preferable. At this point we don't rely on `npm install` after datawrapper deployments, as all vendor libraries are checked into our repo.

So it means we have to include a copy of the dw.js bundle in the `datawrapper` git repo which is sort of the current situation except we're swapping the repo from where we need to pull the file, right? Instead of `chart-core` copying the file from `datawrapper` it means `datawrapper` has to copy the file from `chart-core`.

**Comment by davidkokkelink** [comment]
Given that we now only include it client-side for the chart editor (correct me if I'm wrong!), couldn't we also remove it from the `datawrapper` repo altogether and load it from the frontend server a la `//:{config.frontendDomain}.{config.host}/static/dw-2.0.js`)

**Comment by davidkokkelink** [comment]
Given that the preview now comes from the frontend server it's a non-optional part of the chart editor anyway

**Comment by gka** [comment]
That is true. Maybe it just "feels" wrong to me to move this 8 years old jQuery-infected JS code + weird coffeescript test files plus a severely outdated Grunt task runner into this repo full of fresh Svelte3 code.

**Comment by sto3psl** [comment]
Haha, trust me it felt weird for me too 😄. Since the file is needed that was the most straightforward way for me to include it until it may be gone at some point.

@davidkokkelink's idea sounds good to me and I can implement it if that's ok for everyone.

**Comment by sto3psl** [comment]
Already on it and testing everything. nginx rebuild takes a little

**Pull request merged**
